"""
Web-based GUI setup wizard for AI Job Hunter.
Provides a professional, user-friendly interface for first-time configuration.

Usage: python web_setup_wizard.py
"""

import os
import json
import webbrowser
import threading
import time
from flask import Flask, render_template, request, jsonify
from config_template import (
    ENTRY_LEVEL_INDICATORS, NOISE_KEYWORDS, IGNORE_FIELDS,
    INTEREST_KEYWORDS
)

app = Flask(__name__)
app.config['JSON_SORT_KEYS'] = False

# Store config data during setup
setup_data = {}


@app.route('/')
def index():
    """Serve the setup wizard page."""
    return render_template('setup_wizard.html')


@app.route('/api/defaults')
def get_defaults():
    """Return default values for form fields."""
    return jsonify({
        'noise_keywords': NOISE_KEYWORDS,
        'interest_keywords': INTEREST_KEYWORDS,
        'ignore_fields': IGNORE_FIELDS[:20],  # Show first 20 for preview
        'all_ignore_fields': IGNORE_FIELDS,
        'entry_level': ENTRY_LEVEL_INDICATORS,
    })


@app.route('/api/save-config', methods=['POST'])
def save_config():
    """Save the configuration to config.py."""
    global setup_data
    setup_data = request.json

    config_content = f'''"""
AI Job Hunter Configuration
Auto-generated by web setup wizard

Customize these settings as needed!
"""

# =========================================================================
# 1. YOUR BACKGROUND (Most Important!)
# =========================================================================
YOUR_BACKGROUND = """{setup_data['background']}"""

'''

    if setup_data.get('resume'):
        config_content += f'''
# Additional resume/profile information
RESUME_TEXT = """{setup_data['resume']}"""

'''

    config_content += f'''
# =========================================================================
# 2. SEARCH & FILTERING KEYWORDS
# =========================================================================
SEARCH_QUERIES = {json.dumps(setup_data['search_keywords'], indent=2)}

INTEREST_KEYWORDS = {json.dumps(setup_data['interest_keywords'], indent=2)}

NOISE_KEYWORDS = {json.dumps(setup_data['noise_keywords'], indent=2)}

IGNORE_FIELDS = {json.dumps(setup_data['ignore_fields'], indent=2)}

ENTRY_LEVEL_INDICATORS = {json.dumps(ENTRY_LEVEL_INDICATORS, indent=2)}

# =========================================================================
# 3. LOCATION PREFERENCES
# =========================================================================
STATE_CA_LOCATION = {json.dumps(setup_data['locations'].get('state_ca'))}
STATE_CA_KEYWORDS = {json.dumps(setup_data['search_keywords'], indent=2)}

# =========================================================================
# 4. ENABLED JOB SITES
# =========================================================================
ENABLED_SITES = {{
    "pge": {str(setup_data['sites'].get('pge', True)).lower()},
    "smud": {str(setup_data['sites'].get('smud', True)).lower()},
    "kaiser": {str(setup_data['sites'].get('kaiser', True)).lower()},
    "state_ca": {str(setup_data['sites'].get('state_ca', True)).lower()},
    "commonspirit": {str(setup_data['sites'].get('commonspirit', True)).lower()},
    "sutter": {str(setup_data['sites'].get('sutter', True)).lower()},
    "ucdavis": {str(setup_data['sites'].get('ucdavis', True)).lower()},
}}

# Max pages to scrape per site
PG_E_MAX_PAGES = 20
SMUD_MAX_PAGES = 20
KAISER_MAX_PAGES = 20
STATE_CA_MAX_PAGES = 20
COMMONSPIRIT_MAX_PAGES = 20
SUTTER_MAX_PAGES = 20
UCDAVIS_MAX_PAGES = 20
'''

    try:
        with open('config.py', 'w') as f:
            f.write(config_content)
        return jsonify({'success': True, 'message': 'Configuration saved successfully!'})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500


def open_browser():
    """Open the setup wizard in the default browser after a short delay."""
    time.sleep(2)
    webbrowser.open('http://localhost:5000')


def run_setup_wizard():
    """Run the web-based setup wizard."""
    print("\n" + "="*70)
    print("🚀 AI JOB HUNTER - WEB SETUP WIZARD")
    print("="*70)
    print("\nOpening setup wizard in your browser...\n")
    print("If it doesn't open automatically, go to: http://localhost:5000\n")

    # Open browser in background thread
    browser_thread = threading.Thread(target=open_browser, daemon=True)
    browser_thread.start()

    # Run Flask app
    app.run(debug=False, port=5000, use_reloader=False)


if __name__ == '__main__':
    run_setup_wizard()
